### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by Haydardi** [ping/instagram_private_api#67]
Hi,

Thank you for this amazing web api, however I'm starting to get:
`urllib.error.HTTPError: HTTP Error 403: Forbidden`
on all of my requests. Did Instagram block access to this api?

Here's what I get when I run the get_user:
`instagram_web_api.errors.ClientError: HTTPError "Forbidden" while opening https://www.instagram.com/haydar.aimon/?__a=1`

**Comment by ping** [comment]
@Haydardi

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by Haydardi** [comment]
@ping 

Alright, have done it. Let me know if this is okay now

**Comment by Haydardi** [comment]
@pavloki 

Is it possible to try another url approach you think?

**Comment by 2minchul** [comment]
I solved this problem. I will send a pull request soon.

**Comment by pavloki** [comment]
I wrote small helpful function:
```
def _get_user_info(username):
    # Helper function to temporary replace user_info2
    try:
        url = 'https://instagram.com/%s' % username
        resp = webapi.opener.open(url)

    except HTTPError as e:
        raise ClientError('HTTPError "{0!s}" while opening {1!s}'.format(e.reason, url), e.code)

    resp_html = resp.read().decode('utf-8')
    resp_find = re.findall('<script type="text/javascript">window._sharedData = (.*?);</script>', resp_html)
    resp_json = json.loads(resp_find[0])
    resp_info = resp_json.get('entry_data').get('ProfilePage')[0].get('graphql').get('user')

    return resp_info
```

It is not good solution, but it's work good. And it works slower in twice that old method.

**Comment by Haydardi** [comment]
@2minchul 

That sounds very good, looking forward to it!

@pavloki 
Thanks so much for sharing man, appreciate it!

**Comment by ping** [comment]
@Haydardi Please fix your issue template. You didn't post the code used, you only posted the error trackback, so I cannot tell if you're using an authenticated or unauthenticated client.

@2minchul Thanks for your PR but I already have a similar fix in my local repo, which I'm not pushing out because there's still a bug. Can you test if your fix works when the user is authenticated? In my testing, this works only if the user is unauthenticated (no login). When the user is authenticated, it's still a 403.

**Comment by Haydardi** [comment]
@ping You're right, forgot to write about that. I have updated the issue again. Short answer, I'm using the unauthenticated client.

**Comment by Haydardi** [comment]
@2minchul Your fix works wonders in my case (unauthenticated client)!

**Comment by 2minchul** [comment]
This issue happened again.
new md5 value is 
`{rhx_gis}:{variables}`

**Comment by ping** [comment]
@2minchul Thanks for the tip. Fixed in 5133b823e47d62d1642c4a41d1b1b7bfe0c1ae22

**Comment by Haydardi** [comment]
Awesome! Thanks a lot. 

Quick question. I would love to contribute to this project, especially the web API, but I’m new to this area. What libraries/frameworks should I read about in or to fully understand the web API?

**Comment by lukeify** [comment]
Are Instagram watching this project or something? There's been a number of changes in rapid succession over the past several days, and I've been using this project as a guideline on how to access the unauthenticated endpoints for my own project. 

Thanks to @ping and @2minchul for all the work so far. 

And hello Instagram devs! 😁👋

**Comment by Haydardi** [comment]
Bad news...

I'm still getting the same Forbidden error. What to do?
